CentralBank/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name = "home"),
    url(r'^accounts/', include("accounts.urls")),
    url(r'^profile/', include("profiles.urls")),
    url(r'^admins/', include("admins.urls"))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#Change Site Title, Index Title and Site Title
admin.site.site_header = "Central Bank Administration"
admin.site.site_title = "Central Bank Administration"
admin.site.index_title = "Welcome to Central Bank Administration Admin Panel"

accounts/urls.py
from django.conf.urls import url
from . import views

app_name = "accounts"

urlpatterns = [
    url(r"^register/$", views.register, name = "signup"),
    url(r"^login/$", views.sign_in, name = "signin"),
    url(r"^logout/$", views.logout_view, name = "logout"),
]

admins/urls.py
from django.conf.urls import url
from . import views

app_name = "admins"

urlpatterns = [
    url(r"^$", views.index, name = "admin_index"),
]

profiles/urls.py
from django.conf.urls import url
from . import views

app_name = "profiles"

urlpatterns = [
    url(r"^account_status/$", views.index, name = "account_status"),
    url(r"^money_transfer/", views.money_transfer, name = "money_transfer"),
    url(r"^loan_app/$", views.loan, name = "loan_app"),
    url(r"^ewallet/$", views.ewallet, name = "ewallet"),
    url(r"^online_pay/$", views.online_pay, name = "online_pay"),
    url(r"settings/$", views.settings, name = "settings"),
    url(r"edit_details/", views.edit_details, name = "edit_details"),
    url(r"delete_account/$", views.delete_account, name = "delete_account")
]

profiles/models.py
from django.db import models
import datetime

class BasicDetails (models.Model):
    # (Name, Sex, DOB, Annual income, Email, Mobile number, Occupation) 
    name = models.CharField(max_length = 50, default = None)
    sex = models.CharField(max_length = 1, default = None)
    annual_income = models.IntegerField(default = 0)
    email = models.EmailField(default = None)
    mobile = models.IntegerField(default = 0)
    occupation = models.CharField(max_length = 50, default = None)
    DOB = models.DateField(default = None)
    user_name = models.CharField(max_length = 150, default = None)

class PresentLocation (models.Model):
    # (Country, State, City, Street, Pincode) 
    country = models.CharField(max_length = 50, default = "India")
    state = models.CharField(max_length = 50)
    city = models.CharField(max_length = 50)
    street = models.CharField(max_length = 50)
    pincode = models.IntegerField()
    user_name = models.CharField(max_length = 150, default = None)

class Status (models.Model):
    account_number = models.IntegerField()
    balance = models.IntegerField()
    user_name = models.CharField(max_length = 150, default = None)

class MoneyTransfer(models.Model):
    enter_your_user_name = models.CharField(max_length = 150, default = None)
    enter_the_destination_account_number = models.IntegerField()
    enter_the_amount_to_be_transferred_in_INR = models.IntegerField()

profiles/forms.py
from django import forms
from . import models

class BasicDetailsForm (forms.ModelForm):
    # class to store all the model form fields from models.py
    class Meta:
        model = models.BasicDetails
        fields = ["name", "sex", "DOB", "annual_income", "email", "mobile", "occupation"]


class PresentLocationForm (forms.ModelForm):
    class Meta:
        model = models.PresentLocation
        fields = ["country", "state", "city", "street", "pincode"]

class MoneyTransferForm (forms.ModelForm):
    class Meta:
        model = models.MoneyTransfer
        fields = [
            "enter_your_user_name",
            "enter_the_destination_account_number", 
            "enter_the_amount_to_be_transferred_in_INR"
        ]

profiles/views.py
from django.shortcuts import render, redirect
from . import forms
from . import models
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from profiles.models import Status 
import random

def randomGen():
    # return a 6 digit random number
    return int(random.uniform(100000, 999999))

def index(request):
    try:
        curr_user = Status.objects.get(user_name=request.user) # getting details of current user
    except:
        # if no details exist (new user), create new details
        curr_user = Status()
        curr_user.account_number = randomGen() # random account number for every new user
        curr_user.balance = 0
        curr_user.user_name = request.user
        curr_user.save()
    return render(request, "profiles/profile.html", {"curr_user": curr_user})

def money_transfer(request):
    if request.method == "POST":
        form = forms.MoneyTransferForm(request.POST)
        if form.is_valid():
            form.save()
        
            curr_user = models.MoneyTransfer.objects.get(enter_your_user_name=request.user)
            dest_user_acc_num = curr_user.enter_the_destination_account_number

            temp = curr_user # NOTE: Delete this instance once money transfer is done
            
            dest_user = models.Status.objects.get(account_number=dest_user_acc_num) # FIELD 1
            transfer_amount = curr_user.enter_the_amount_to_be_transferred_in_INR # FIELD 2
            curr_user = models.Status.objects.get(user_name=request.user) # FIELD 3

            # Now transfer the money!
            curr_user.balance = curr_user.balance - transfer_amount
            dest_user.balance = dest_user.balance + transfer_amount

            # Save the changes before redirecting
            curr_user.save()
            dest_user.save()

            temp.delete() # NOTE: Now deleting the instance for future money transactions

        return redirect("profiles/profile.html")
    else:
        form = forms.MoneyTransferForm()
    return render(request, "profiles/money_transfer.html", {"form": form})

def loan(request):
    return render(request, "profiles/loans.html")

def ewallet(request):
    return render(request, "profiles/eWallet.html")

def online_pay(request):
    return render(request, "profiles/online_payment.html")

def settings(request):
    return render(request, "profiles/settings.html")

def edit_details(request):
    if request.method == "POST":
        # POST actions for BasicDetailsForms
        try:
            curr_user = models.BasicDetails.objects.get(user_name=request.user)
            form = forms.BasicDetailsForm(request.POST, instance=curr_user)
            if form.is_valid():
                form.save()
        except:
            form = forms.BasicDetailsForm(request.POST)
            if form.is_valid():
                form = form.save(commit=False)
                form.user_name = request.user
                form.save()

        # POST actions for PresentLocationForm
        try:
            curr_user = models.PresentLocation.objects.get(user_name=request.user)
            form = forms.PresentLocationForm(request.POST, instance=curr_user)
            if form.is_valid():
                form.save()
        except:
            form = forms.PresentLocationForm(request.POST)
            if form.is_valid():
                form = form.save(commit=False)
                form.user_name = request.user
                form.save()     
        
        # POST actions for Password change
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below.')

        return redirect("profiles/edit_details.html")
    
    else: # GET actions
        try:
            curr_user = models.BasicDetails.objects.get(user_name=request.user)
            form1 = forms.BasicDetailsForm(instance=curr_user) # basic details
        except:
            form1 = forms.BasicDetailsForm()
        
        try:
            curr_user = models.PresentLocation.objects.get(user_name=request.user)
            form2 = forms.PresentLocationForm(instance=curr_user) # location
        except:
            form2 = forms.PresentLocationForm()

        # change password
        form3 = PasswordChangeForm(request.user)

        dici = {"form1": form1, "form2": form2, "form3": form3}
        return render(request, "profiles/edit_details.html", dici)

def delete_account(request):
    return render(request, "profiles/delete_account.html")

profiles/templates/profiles/delete_account.html
{% extends 'profiles/profile_base_layout.html' %}

{% block headcontent %}
    <style>
        @import url('https://fonts.googleapis.com/css?family=Cinzel|PT+Serif');
        
        body {
            background-color: floralwhite;
        }
        h2 {
            font-family: "PT Serif";
        }

        #side_panel
        {
            font-size: 16px;
            font-family: "Titillium Web";
            background-color: rgb(170, 95, 57);
            margin-top: -7px;
            margin-left: -10px;
            height: 540px;
            overflow-x: auto;
            overflow-y: auto;
        }
        
        .side {
            color: aliceblue;
        }
        .side:hover {
            color: mediumaquamarine;
        }
        .warning {
            color: yellow;
        }
        .danger {
            color: #FF8723;
            font-weight: 900;
        }
        .current {
            border: 1px solid;
            padding: 3px;
        }
        .curr_bal {
            font-family: "Cinzel";
            font-weight: 600;
        }
        .g-recaptcha {
            width: 50px;
        }
        
        #side_panel::-webkit-scrollbar {
            width: 7px;
        }
        #side_panel::-webkit-scrollbar:hover {
            width: 12px;
        }
        #side_panel::-webkit-scrollbar-track {
            -webkit-box-shadow: inset 0 0 3px rgba(0,0,0,0.3);
            border-radius: 10px;
        }
        ::-webkit-scrollbar-thumb {
            border-radius: 10px;
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
        }
    </style>
    
    <script src='https://www.google.com/recaptcha/api.js'></script>
{% endblock %}

{% block bodycontent %}
    <section id="welcome_post" class="col-9">   
        <h3 style="font-weight: 300;" >Deleting the account means:</h3>
        <ul type="square">
            <li>Permanent loss of your account balance (so <a href="{% url 'profiles:money_transfer' %}">transfer your money</a> to a different account first). </li>
            <li>Permanent loss of your account data, settings, and details.</li>
        </ul>

        <h3 style="font-weight: 300;" >By pressing the following button, you understand the shortcomings as described in <a href="#">here</a>. </h3>
        
        
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#delete" >
            Take me to deletion
        </button>

        <!-- Modal -->
        <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="delete" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirm deletion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <form>
                    <div class="modal-body">
                        Enter password to confirm deletion
                        <input type="password" class="form-control" required>
                        <br>
                        Prove you are a human
                        <div class="g-recaptcha" data-sitekey="6Ld_qjQUAAAAADjv2scrqpvXK4OrBZALRJFMANpP"></div>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Delete my account</button>
                    </div>
                </form>
                
            </div>
            </div>
        </div>
        
        
    </section>
{% endblock %}

{% block scriptcontent %}
    <script>
        $(".current").removeClass("current");
        $("#delete").addClass("current");
    </script>
{% endblock %}

profiles/templates/profiles/edit_details.html
{% extends 'profiles/profile_base_layout.html' %}

{% block headcontent %}
        <style>
            @import url('https://fonts.googleapis.com/css?family=Cinzel|PT+Serif');
            
            body {
                background-color: floralwhite;
            }
            h2 {
                font-family: "PT Serif";
            }

            #side_panel
            {
                font-size: 16px;
                font-family: "Titillium Web";
                background-color: rgb(170, 95, 57);
                margin-top: -7px;
                margin-left: -10px;
                height: 540px;
                overflow-x: auto;
                overflow-y: auto;
            }
            
            .side {
                color: aliceblue;
            }
            .side:hover {
                color: mediumaquamarine;
            }
            .warning {
                color: yellow;
            }
            .danger {
                color: #FF8723;
                font-weight: 900;
            }
            .current {
                border: 1px solid;
                padding: 3px;
            }
            .curr_bal {
                font-family: "Cinzel";
                font-weight: 600;
            }
            
            #side_panel::-webkit-scrollbar {
                width: 7px;
            }
            #side_panel::-webkit-scrollbar:hover {
                width: 12px;
            }
            #side_panel::-webkit-scrollbar-track {
                -webkit-box-shadow: inset 0 0 3px rgba(0,0,0,0.3);
                border-radius: 10px;
            }
            ::-webkit-scrollbar-thumb {
                border-radius: 10px;
                -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
            }
        </style>
        
        <script src='https://www.google.com/recaptcha/api.js'></script>
{% endblock %}

{% block bodycontent %}
    <section id="welcome_post" class="col-9">                
        <h4 style="font-weight: 300;" >
            Only the following details can be edited. For the rest, kindly visit the bank in person.
        </h4>
        <br>
        
        <!-- EDIT BASIC DETAILS -->
        <a href="#basic" class="btn btn-primary btn-block" data-toggle="modal" data-target="#basic">Edit basic</a>
        <div class="modal fade" id="basic" tabindex="-1" role="dialog" aria-labelledby="basic" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit basic details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <form action="{ url 'profiles:edit_details' }" method="post" enctype="multipart/form-data" id="basic-form">
                    <div class="modal-body">
                       

                        {% csrf_token %}
                        {{ form1 }}
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Edit details</button>
                    </div>
                </form>
                
            </div>
            </div>
        </div>
        
        
        (Email, Mobile number, Occupation)
        <br> <br>
        
        <!-- EDIT PRESENT LOCATION -->
        <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#location">Edit present location</button>
        
        <div class="modal fade" id="location" tabindex="-1" role="dialog" aria-labelledby="location" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit present location</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <form action="{ url 'profiles:edit_details' }" method="post" enctype="multipart/form-data" id="location">
                    <div class="modal-body">
                        {% csrf_token %}
                        {{ form2 }}
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Edit details</button>
                    </div>
                </form>
                
            </div>
            </div>
        </div>
        (Country, State, City, Street, Pincode)
        <br> <br>
        
        <!-- EDIT ACCOUNT DETAILS -->
        <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#account">Edit account details</button> 
        <div class="modal fade" id="account" tabindex="-1" role="dialog" aria-labelledby="account" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit account type</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                    Account type: <br>
                    <input type="radio" checked> Savings
                    <br>
                    <span class="small">(Presently, we only support Savings accounts)</span>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
                
            </div>
            </div>
        </div>
        (Account type)
        <br> <br>
        
        <!-- EDIT PASSWORD -->
        <button type="button" class="btn btn-success btn-block" data-toggle="modal" data-target="#password">Edit password</button>
        <div class="modal fade" id="password" tabindex="-1" role="dialog" aria-labelledby="password" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit password</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <form>
                    <div class="modal-body">
                        
                        {% csrf_token %}
                        {{ form3 }}
                        Prove you are human
                        <div class="g-recaptcha" data-sitekey="6Ld_qjQUAAAAADjv2scrqpvXK4OrBZALRJFMANpP"></div>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Update password</button>
                    </div>
                </form>
                
            </div>
            </div>
        </div>    
        
    </section>
{% endblock %}

{% block scriptcontent %}
    <script>
        $(".current").removeClass("current");
        $("#details").addClass("current");

        $("input").addClass("form-control");
        $("input[type=radio]").removeClass("form-control");
    </script>
{% endblock %}

profiles/templates/profiles/loans.html
{% extends 'profiles/profile_base_layout.html' %}

{% block headcontent %}
    <style>
        @import url('https://fonts.googleapis.com/css?family=Cinzel|PT+Serif');
        
        body {
            background-color: floralwhite;
        }
        h2 {
            font-family: "PT Serif";
        }

        #side_panel
        {
            font-size: 16px;
            font-family: "Titillium Web";
            background-color: rgb(170, 95, 57);
            margin-top: -7px;
            margin-left: -10px;
            height: 540px;
            overflow-x: auto;
            overflow-y: auto;
        }
        
        .side {
            color: aliceblue;
        }
        .side:hover {
            color: mediumaquamarine;
        }
        .warning {
            color: yellow;
        }
        .danger {
            color: #FF8723;
            font-weight: 900;
        }
        .current {
            border: 1px solid;
            padding: 3px;
        }
        .curr_bal {
            font-family: "Cinzel";
            font-weight: 600;
        }
        
        #side_panel::-webkit-scrollbar {
            width: 7px;
        }
        #side_panel::-webkit-scrollbar:hover {
            width: 12px;
        }
        #side_panel::-webkit-scrollbar-track {
            -webkit-box-shadow: inset 0 0 3px rgba(0,0,0,0.3);
            border-radius: 10px;
        }
        ::-webkit-scrollbar-thumb {
            border-radius: 10px;
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
        }
    </style>
{% endblock %}

{% block bodycontent %}
    <section id="welcome_post" class="col-9">
        <h2>Welcome, <span id="prof_name">{{ user }}.</span> </h2>
        <h4 style="font-weight: 300;">It's good to have you here.</h4>   
        <br>   
        
        <form>
            <h3 style="font-weight: 300;">
                What do you need the loan for?
                <input type="text" class="form-control" id="loan_type" required>
            </h3>
            <br>
            <h3 style="font-weight: 300;">
                Enter the amount of loan needed (₱)
                <input type="number" class="form-control" id="loan_amt" required>
            </h3>
            <small>Please read the <a href="#">Terms and Conditions</a> before requesting for loan</small>. <br>
            <button class="btn btn-primary" type="button" id="loan_submit">Request loan</button>
        </form>
        
    </section>
{% endblock %}         

{% block scriptcontent %}
    <script>
        $(".current").removeClass("current");
        $("#loan").addClass("current");

        $("#loan_submit").click(function() {
            var msg = "Your loan has been requested. You'll be notified if it gets approved in 24 hours. Press OK."
            
            if(
                $("#loan_type").val() =="" || 
                $("#loan_amt").val() == ""
            )
                    msg = "Error: One or more of the required fields is missing";
                
            
            alert(msg);
        });
    </script>
{% endblock %}

profiles/templates/profiles/money_transfer.html
{% extends 'profiles/profile_base_layout.html' %}

{% block headcontent %}
    <style>
        @import url('https://fonts.googleapis.com/css?family=Cinzel|PT+Serif');
        
        body {
            background-color: floralwhite;
        }
        h2 {
            font-family: "PT Serif";
        }

        #side_panel
        {
            font-size: 16px;
            font-family: "Titillium Web";
            background-color: rgb(170, 95, 57);
            margin-top: -7px;
            margin-left: -10px;
            height: 540px;
            overflow-x: auto;
            overflow-y: auto;
        }
        
        .side {
            color: aliceblue;
        }
        .side:hover {
            color: mediumaquamarine;
        }
        .warning {
            color: yellow;
        }
        .danger {
            color: #FF8723;
            font-weight: 900;
        }
        .current {
            border: 1px solid;
            padding: 3px;
        }
        .curr_bal {
            font-family: "Cinzel";
            font-weight: 600;
        }
        
        #side_panel::-webkit-scrollbar {
            width: 7px;
        }
        #side_panel::-webkit-scrollbar:hover {
            width: 12px;
        }
        #side_panel::-webkit-scrollbar-track {
            -webkit-box-shadow: inset 0 0 3px rgba(0,0,0,0.3);
            border-radius: 10px;
        }
        ::-webkit-scrollbar-thumb {
            border-radius: 10px;
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
        }
    </style>
{% endblock %}
        
{% block bodycontent %}
    <section id="welcome_post" class="col-9">
        <h2>Welcome, <span id="prof_name">{{ user }}.</span> </h2>
        <h4 style="font-weight: 300;">It's good to have you here.</h4>   

        <form action="{ url 'profiles:money_transfer' }" method="post">
            {% csrf_token %}

            <h3 style="font-weight: 300;">
                {{ form }}
            </h3>
            
            <small>By transferring money from your account, you agree to the <a href="#">Terms and Conditions</a> of amount transfer</small>. <br>
            <button type="submit" class="btn btn-danger">Transfer amount</button>
        </form>
    </section>
{% endblock %}

{% block scriptcontent %}
    <script>
        $(".current").removeClass("current");
        $("#transfer").addClass("current");

        $("input").addClass("form-control");
        $("label").prepend("<br>")
    </script>
{% endblock %}

profiles/templates/profiles/profile_base_layout.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>Neptune Bank | Profile</title>
        
        <!-- CSS FRAMEWORKS REQUIRED -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        <!-- STYLINGS -->
        <link rel="stylesheet" href="/static/common-styles.css">
        
        {% block headcontent %}
        {% endblock %}
        
    </head>
    
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-success">
            <img src="/static/images/homepage.png" width="50px">
            <a class="navbar-brand" href="index.html">&nbsp;Neptune Bank</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </div>
            </div>
        </nav>
        
        <br> <br> <br>
       
        <div class="container-fluid row">
        
                <!--SIDE PANEL BEGINS -->
                <section id="side_panel" class="col-3 bg-dark">
                    <img src="/static/images/adminlogo.png" class="container btn">
                    <!-- OPERATIONS -->
                    <a href="{% url 'profiles:account_status' %}" class="current side" id="status">Account status</a> <br> <br>
                    
                    <a href="{% url 'profiles:money_transfer' %}" class="side" id="transfer">Money Transfer</a> <br> <br>
                    
                    <a href="{% url 'profiles:loan_app' %}" class="side" id="loan">Loan application</a> <br> <br>
                    
                    
                    
                    <a href="{% url 'profiles:settings' %}" class="side" id="settings">Account settings</a> <br> <br>
                    
                    <a href="{% url 'profiles:edit_details' %}" class="side warning" id="details">Edit account details</a> <br> <br>
                    
                    <a href="{% url 'profiles:delete_account' %}" class="side danger" id="delete">Delete account</a> <br> <br>                
                </section>
                <!-- SIDE PANEL ENDS -->
        
                {% block bodycontent %}
                {% endblock %}

            </div>
       
        <!-- FOOTER -->
        <section class="foot bg-success text-white">
            <div class="text-center">
                &copy; Website created with <i class="fa fa-heart" style="color: red;"></i> by <a href="https://itsourcecode.com/rafi007akhtar" target="_blank">Itsourcecode</a>    
                <br>
                <i></i><a>&copy; Bank Management System 2021</a>
            </div>
        </section>   
        
        <!-- JS LIBRARIES REQUIRED -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

        {% block scriptcontent %}
        {% endblock %}
    </body>
</html>