CentralBank/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name = "home"),
    url(r'^accounts/', include("accounts.urls")),
    url(r'^profile/', include("profiles.urls")),
    url(r'^admins/', include("admins.urls"))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#Change Site Title, Index Title and Site Title
admin.site.site_header = "Central Bank Administration"
admin.site.site_title = "Central Bank Administration"
admin.site.index_title = "Welcome to Central Bank Administration Admin Panel"

accounts/urls.py
from django.conf.urls import url
from . import views

app_name = "accounts"

urlpatterns = [
    url(r"^register/$", views.register, name = "signup"),
    url(r"^login/$", views.sign_in, name = "signin"),
    url(r"^logout/$", views.logout_view, name = "logout"),
]

admins/urls.py
from django.conf.urls import url
from . import views

app_name = "admins"

urlpatterns = [
    url(r"^$", views.index, name = "admin_index"),
]

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>Bank Management System</title>
        
        <!-- CSS FRAMEWORKS REQUIRED -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        {% block stylecontent %}

        {% endblock %}
        
        <link rel="stylesheet" href="/static/common-styles.css">

    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top">
            <img src="/static/images/homepage.png" width="50px">
            <a class="navbar-brand" href="{% url 'home' %}">&nbsp;Neptune Bank Website</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link active" href="{% url 'home' %}" id="nav-home">Home</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:signup' %}" id="nav-create">Create new account</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:signin' %}" id="nav-login">Sign In</a>
                </div>
            </div>
        </nav>
        
        <br> <br> <br>

        {% block bodycontent %}

        {% endblock %}
        
        <!-- FOOTER -->
        <section class="foot bg-success text-white">
            <div class="text-center">
                &copy; Website created with <i class="fa fa-heart" style="color: red;"></i> by <a href="https://itsourcecode.com/rafi007akhtar" target="_blank">Itsourcecode</a>    
                <br>
                <i></i><a>&copy; Bank Management System 2021</a>
            </div>
        </section>    
        
        <!-- JS LIBRARIES REQUIRED -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

        {% block scriptcontent %}
        {% endblock %}
        
    </body>
</html>

templates/index.html
{% extends 'base_layout.html' %}

{% block stylecontent %}
    <style>
        h1 {
            border-bottom: 1px solid;
        }
        h4 {
            font-weight: 400;
        }
        a:hover {
            text-decoration: none;
        }
        
        .foot {
            position: absolute;
            bottom: 0px;
            left: 0px;
            right: 0px;
        }
    </style>
{% endblock %}
        

{% block bodycontent %}    
    <div class="container text-center">
        <h1>Welcome to Neptune Bank</h1>
        <h4><em>We Do Not Delay Your Transaction</em></h4>
    </div>
    
    <br>
    
    <div class="container">
        <a href="{% url 'accounts:signup' %}"><button class="btn btn-primary btn-block" id="acc"><i class="fa fa-user"></i> Create new account</button></a>
        <br> 
        <a href="{% url 'accounts:signin' %}"><button class="btn btn-danger btn-block" id="sign_in"><i class="fa fa-sign-in"></i> Sign in</button></a>
    </div>
    
    <br>
{% endblock %}